### ISSUE TITLE
Some reference libraries are missing at runtime. I tried to find the missing dll, but the game still prompts an error. I hope you can provide the correct library version, such as Ookii’s

### ISSUE THREAD

**Issue by chilamkatana** [Doddler/RagnarokRebuildTcp#2]
Some reference libraries are missing at runtime. I tried to find the missing dll, but the game still prompts an error. I hope you can provide the correct library version, such as Ookii’s

**Comment by Doddler** [comment]
I'm a little late on noticing, but you are correct, git wasn't seeing the dll files. Odd since they aren't in the gitignore, but at any rate I added the dlls for the StandaloneFileManager (though I'm not even sure I'm using that one atm) and the websocket library. At some point I should clean it up and make sure the repository can be fully loaded without needing fixes.
